# Example dataset configuration demonstrating simplified structure
# Inherits directly from dataset_default.yaml, which shows all possible parameters and their defaults.
defaults:
  - dataset_default.yaml
  - _self_

# =============================================================================
# DATASET METADATA
# =============================================================================
dataset:
  name: "demo_dataset"
  description: "CellxGene pseudo bulk dataset with 10k samples. Annotated with natural language descriptions obtained in CellWhisperer Study."
  download_url: "https://nxc-fredato.imbi.uni-freiburg.de/s/NgRiaxRMWqsaiZg/download" # Example URL
  full_name: "cellxgene_pseudo_bulk_subset" #This example data is already a subset of the full data.

# =============================================================================
# COMMON KEYS (dataset-specific)
# =============================================================================
batch_key: "dataset_title"
annotation_key: "cell_type"
caption_key: "natural_language_annotation"
instrument_key: "assay"
other_bio_labels: ["tissue", "disease"]

# =============================================================================
# DATASET-LEVEL CONFIGURATION
# =============================================================================
# Training vs Test dataset configuration (applies to both preprocessing and dataset creation)
split_dataset: true # true = training dataset with train/val split, false = test dataset with "all" split

# =============================================================================
# DATASET-SPECIFIC OVERRIDES
# =============================================================================
# Download configuration
download:
  enabled: true
  subset_size: 10000
  stratify_keys: null # List of column names to stratify by (will be auto-generated from common keys)
  preserve_proportions: true # When subsetting, preserve the proportions of classes

# Preprocessing overrides (both dataset-specific and execution parameters)
# More parameters can be found in dataset_default.yaml
preprocessing:
  enabled: true
  chunk_size: 100000 # If larger than the dataset, there will be one chunk.
  count_layer_key: "counts" # Key in adata.layers with raw counts. If not present, adata.raw.X is checked.

# Embedding preparation overrides
embedding_preparation:
  enabled: false # Set to false to skip embedding preparation
  methods: ["geneformer-v1"] #run the prepare step on cpu to save gpu time

# Embedding overrides (both dataset-specific and execution parameters)
embedding_cpu:
  enabled: true
  methods: ["pca", "scvi_fm", "gs10k"]

embedding_gpu:
  enabled: false
  methods: ["geneformer-v1"]

# Dataset creation overrides
dataset_creation:
  enabled: true
  use_nextcloud: true
  dataset_format: "multiplets" # "multiplets" for training datasets, "single" for test datasets
  # Dataset-specific parameters
  required_obsm_keys: ["X_pca", "X_scvi_fm", "X_gs10k", "X_geneformer-v1"] #, "X_geneformer"]
  cs_length: [4096]
  caption_keys: ["caption_key"] #here you could also use a different key, like annotation_key, to include not captions but annotations into the dataset. If you do both, two datasets will be created.
  negatives_per_sample: 2
  resolve_negatives: false # If true, resolve negative indices to content (only works with single sentence_key)
