# Input file path (preprocessed data)
# Support both .h5ad and .zarr formats
#input_files:
#  - "data/RNA/processed/train/cellxgene_pseudo_bulk_3_5k/all_train.h5ad"
#  - "data/RNA/processed/train/cellxgene_pseudo_bulk_3_5k/all_val.h5ad"
input_files:
  - "data/RNA/processed/train/cellxgene_pseudo_bulk_3_5k/train/chunk_0.zarr"
  - "data/RNA/processed/train/cellxgene_pseudo_bulk_3_5k/val/chunk_0.zarr"

# -----------------------------------------------------------------------------
# File format configuration
# input_format: "auto" (detect from extension), "h5ad", or "zarr"
# output_format: "zarr" (default) or "h5ad"
# -----------------------------------------------------------------------------
input_format: auto # Default: auto-detect from file extension
output_format: zarr # Default: zarr for better performance and streaming

# per default, the output dir is build based on the input file name
output_dir: null
# Embedding method to use
# A list with some of: ["scvi_fm", "geneformer", "pca", "hvg"]
methods: ["hvg"] #["scvi_fm", "pca", "hvg"] #["geneformer"] #

# Batch key in adata.obs (used by scvi_fm)
batch_key: "dataset_title"
# batch sized used by geneformer
batch_size: 16
# Optional: Override default cache directories
# If not specified, will use system-appropriate user cache directories
# cache_dir: "path/to/custom/model/cache"
# file_cache_dir: "path/to/custom/data/cache"

# Number of cells to process at once
chunk_size: 100000

# Dimension of the embedding
embedding_dim_map:
  scvi_fm: 50
  geneformer: 512
  pca: 50
  hvg: 512

# Whether to overwrite existing embeddings
overwrite: false
