# conf/embed_prepare.yaml
# -----------------------------------------------------------------------------
# Defaults for prepare_embed_adata.py
# -----------------------------------------------------------------------------
# You can override any of these on the CLI, e.g.:
#   python3 scripts/prepare_embed_adata.py ++methods='["hvg","pca"]' ++batch_size=64

defaults:
  - _self_

# -----------------------------------------------------------------------------
# Input files: list of one or more .h5ad or .zarr paths to process.
# Use CLI override: ++input_files='["path/to/a.h5ad","path/to/b.zarr"]'
# -----------------------------------------------------------------------------
input_files:
  - data/RNA/processed/train/cellxgene_pseudo_bulk_3_5k/train/chunk0.zarr

# -----------------------------------------------------------------------------
# File format configuration
# input_format: "auto" (detect from extension), "h5ad", or "zarr"
# -----------------------------------------------------------------------------
input_format: auto # Default: auto-detect from file extension

# -----------------------------------------------------------------------------
# Which embedding methods to prepare
# Override with: ++methods='["hvg","pca","scvi_fm"]'
# -----------------------------------------------------------------------------
methods:
  - geneformer

# -----------------------------------------------------------------------------
# Batch settings
# -----------------------------------------------------------------------------
batch_key: dataset_title
batch_size: 32

# -----------------------------------------------------------------------------
# Map each method name to its embedding dimension
# Must include an entry for every method in `methods`
# -----------------------------------------------------------------------------
embedding_dim_map:
  geneformer: 512
