# Test dataset configuration for workflow testing
# Inherits from dataset_default_test.yaml for test-specific defaults
# TESTING PRE-VALIDATION - This should trigger a sync error
defaults:
  - dataset_default_test.yaml
  - workflow_orchestrator.yaml
  - _self_

# =============================================================================
# DATASET METADATA
# =============================================================================
dataset:
  name: "test_workflow"
  description: "Test dataset for workflow orchestration"
  download_url: https://datasets.cellxgene.cziscience.com/bbf12ff4-7f22-4cf5-83cf-9cd37ce4d6f4.h5ad
  file_path: "data/RNA/raw/test/test_workflow.h5ad"
  full_name: "test_workflow_full"

# =============================================================================
# COMMON KEYS (defined once, used across workflows)
# =============================================================================
# Batch key for batch-aware processing
batch_key: "batch"

# Annotation key for cell type/annotation
annotation_key: "cell_type"

# Caption/description key for natural language descriptions
caption_key: null # No captions for test

# Instrument key for technical metadata
instrument_key: "assay"

# Other biological labels for consolidation and plotting
other_bio_labels: ["tissue"]

# =============================================================================
# DOWNLOAD OVERRIDES
# =============================================================================
download:
  enabled: true # Enable download for testing
  subset_size: 1000 # Small subset for testing
  seed: 42

# =============================================================================
# PREPROCESSING OVERRIDES
# =============================================================================
preprocessing:
  enabled: true # Enable preprocessing for testing
  split_dataset: false # No split for test
  chunk_size: 50000 # Small chunks for testing

# =============================================================================
# EMBEDDING OVERRIDES
# =============================================================================
embedding:
  enabled: false # Disable embedding for testing

# =============================================================================
# DATASET CREATION OVERRIDES
# =============================================================================
dataset_creation:
  enabled: false # Disable dataset creation for testing

# =============================================================================
# WORKFLOW OVERRIDES
# =============================================================================
workflow:
  local_mode: true # Force local mode for testing
